title:              "사과양의 사주는 과학이다"
tagline:            "통계학 기반의 학문 음양오행론 소개"
email:              "areum4581@daum.net"
description:        "사주팔자의 동양철학 원리로 성격유형 해석이 가능합니다."
author:             "사과양"
baseurl:            "/"
url:                "https://apple-yang.xyz/"
locale:             "ko_KR"
thumbnail:          "/img/sns-thumb.jpg"

# Social Profiles
twitter_username:   ElleDriver14
instagram_username: sajuyang
facebook_username:  %EC%82%AC%EC%A3%BC%ED%8C%94%EC%9E%90-%EC%82%AC%EC%A3%BC%EC%96%91%EC%9D%98-%EC%82%AC%EC%A3%BC%EB%8A%94-%EA%B3%BC%ED%95%99%EC%9D%B4%EB%8B%A4-106092998372824
linkedin_username:  areum4581

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname:  areum4581
